### ISSUE TITLE
About Project Layout

### ISSUE THREAD

**Issue by ikb4l** [bobrossrtx/TinyKernel#4]
When I reviewed the project, I saw a few things that weren't right. I want to share these with you:
- The `inb(uint16)` and `outb(uint16, uint16)` methods defined in the `src/kernel/keyboard/keyboard.c` file are not directly related to the keyboard. It's about CPU ports. Move these functions to a different location.
- There is absolutely no need for `next_line_index` in `src/sys/vga.c`. Make the VGA driver better, update. The VGA driver needs to be improved as soon as possible!

**Comment by bobrossrtx** [comment]
Thanks alot @ikb4l, Ill look into it and work on it

**Comment by bobrossrtx** [comment]
I have moved the `inb(uint16)` & `outb(uint16, uint16)` functions to `src/kernel/cpu/ports.c` & removed all next_line_index references inside of `src/sys/vga.c`
